<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>agda</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Agda</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(module|where|open|import|data|type|record|field|postulate|with)\b</string>
			<key>name</key>
			<string>keyword.other.agda</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.agda</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.agda</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#dashComment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pragma</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blockComment</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockComment</key>
		<dict>
			<key>begin</key>
			<string>{-</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>-}</string>
			<key>name</key>
			<string>comment.block.agda</string>
		</dict>
		<key>dashComment</key>
		<dict>
			<key>begin</key>
			<string>(--) </string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.double-dash.agda</string>
		</dict>
		<key>pragma</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>\{-#</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.pragma.agda</string>
				</dict>
			</dict>
			<key>end</key>
			<string>#-\}</string>
			<key>name</key>
			<string>support.pragma.block.agda</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.agda</string>
	<key>uuid</key>
	<string>D4DB4FD3-9973-43F6-870E-2B23A41F6B34</string>
</dict>
</plist>
